networks:
  cache-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  cache:
    command: ["redis-server", "--requirepass", "{{PASSWORD}}"]
    container_name: cache
    image: redis:8.2
    networks:
      cache-network:
        ipv4_address: 172.28.0.2
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - cache-data:/data

volumes:
  cache-data:
    driver: local